### ISSUE TITLE
Please register snap name

### ISSUE THREAD

**Issue by om26er** [snapcrafters/android-studio-canary#1]
@popey we need to register `android-studio-canary` snap name and get automatic builds for this repository. We will then request for classic confinement for this.

**Comment by popey** [comment]
Done. 
```
$ lxc shell snapcrafters
mesg: ttyname failed: Success
root@snapcrafters:~# snapcraft register android-studio-canary

We always want to ensure that users get the software they expect
for a particular name.

If needed, we will rename snaps to ensure that a particular name
reflects the software most widely expected by our community.

For example, most people would expect ‘thunderbird’ to be published by
Mozilla. They would also expect to be able to get other snaps of
Thunderbird as 'thunderbird-$username'.

Would you say that MOST users will expect 'android-studio-canary' to come from
you, and be the software you intend to publish there? [y/N]: y
Registering android-studio-canary.
Congrats! You are now the publisher of 'android-studio-canary'.
```

**Comment by popey** [comment]
![image](https://user-images.githubusercontent.com/1841272/51063229-f5674c00-15f1-11e9-8f03-7d8faadaba0d.png)

Building soon!

**Comment by popey** [comment]
@om26er This requires classic to be allowed in the store. Could you please request it, citing the existing android studio snap as also being classic.

**Comment by om26er** [comment]
Already did: https://forum.snapcraft.io/t/classic-confinement-for-android-studio-canary/9418

**Comment by popey** [comment]
D'oh! Thanks! Sorry I missed it.
