### ISSUE TITLE
2021.1.1.2 is latest

### ISSUE THREAD

**Issue by popey** [snapcrafters/android-studio-canary#13]
Store has 4.2.0.23 in the stable channel. 2021.1.1.2 is latest upstream release.

**Comment by popey** [comment]
2021.1.1.3 is now latest upstream. Stable channel has 4.2.0.23

**Comment by om26er** [comment]
Hey @igorljubuncic can you please grant permission to `android-studio-canary` snap in the store. Then I should be able to update that as well.

**Comment by om26er** [comment]
I now have the permissions. I have triggered a new build now, will test that a bit and publish it

**Comment by om26er** [comment]
This is fixed now
