### ISSUE TITLE
Android Studio Canary Snap is Old

### ISSUE THREAD

**Issue by alenz316** [snapcrafters/android-studio-canary#5]
The current snap of the canary build is 3.6.0.9 and was last updated 10/23/2019, while the stable build of Android Studio snap has already passed that and is on 3.6.0.21. - https://github.com/snapcrafters/android-studio

**Comment by alenz316** [comment]
I would love to help out if it's just a matter of capacity for the maintainers.

**Comment by om26er** [comment]
@alenz316 Sorry, we missed to update the canary builds. I have now created a PR, which once landed will start a new build https://github.com/snapcrafters/android-studio-canary/pull/6

**Comment by om26er** [comment]
@popey would it make sense to promote the canary edge build to "stable". For correctness sake, we can't really call a canary build "stable".

**Comment by popey** [comment]
I understand the rationale not to put it in stable. However this is an upstream "stable" release of the canary of Android Studio, so I think it fits in stable channel.
